apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-label-updater
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-label-updater
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: pod-label-updater
  apiGroup: rbac.authorization.k8s.io
