FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && rm -rf /var/lib/apt/lists/*
COPY bin/tentacle-mqtt /usr/local/bin/tentacle-mqtt
RUN chmod +x /usr/local/bin/tentacle-mqtt
ENTRYPOINT ["/usr/local/bin/tentacle-mqtt"]
