FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && rm -rf /var/lib/apt/lists/*
COPY bin/tentacle-ethernetip /usr/local/bin/tentacle-ethernetip
RUN chmod +x /usr/local/bin/tentacle-ethernetip
ENTRYPOINT ["/usr/local/bin/tentacle-ethernetip"]
